name: Run Gradle on PRs
on: push
jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Unit Test
        run: ./gradlew test
